[tools]
task = '3.43.3'
go = '1.24.3'
goreleaser = '2.9.0'
act = '0.2.77'
'golangci-lint' = '2.1.6'
'ubi:dominikh/go-tools' = { version = '2025.1.1', exe = 'staticcheck', tar_regex = '^staticcheck_\.' }
'ubi:psampaz/go-mod-outdated' = '0.9.0'
#'go:golang.org/x/pkgsite/cmd/pkgsite' = 'latest'
