[tools]
task = '3.44.0'
go = '1.24.4'
goreleaser = '2.10.2'
act = '0.2.78'
'golangci-lint' = '2.1.6'
'ubi:dominikh/go-tools' = { version = '2025.1.1', exe = 'staticcheck', tar_regex = '^staticcheck_\.' }
'ubi:psampaz/go-mod-outdated' = '0.9.0'
#'go:golang.org/x/pkgsite/cmd/pkgsite' = 'latest'
