[tools]
task = '3.44.1'
go = '1.25.0'
goreleaser = '2.11.2'
act = '0.2.80'
'golangci-lint' = '2.4.0'
'ubi:dominikh/go-tools' = { version = '2025.1.1', exe = 'staticcheck', tar_regex = '^staticcheck_\.' }
'ubi:psampaz/go-mod-outdated' = '0.9.0'
#'go:golang.org/x/pkgsite/cmd/pkgsite' = 'latest'
