[tools]
task = '3.42.1'
go = '1.24.2'
goreleaser = '2.8.2'
act = '0.2.76'
'golangci-lint' = '2.0.2'
'ubi:dominikh/go-tools' = { version = '2025.1.1', exe = 'staticcheck', tar_regex = '^staticcheck_\.' }
'ubi:psampaz/go-mod-outdated' = '0.9.0'
#'go:golang.org/x/pkgsite/cmd/pkgsite' = 'latest'
